module.exports = {
    production: {
        devtool: false,
        NODE_ENV: 'production',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        filePath: 'dist/',
        staticPath: '/',
        cssPath: '',
        imgPath: '',
        filenameHash: true,
    },
    pre: {
        devtool: false,
        NODE_ENV: 'pre',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        filePath: 'dist/',
        staticPath: '/',
        cssPath: '',
        imgPath: '',
        filenameHash: true,
    },
    test: {
        devtool: false,
        NODE_ENV: 'test',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        filePath: 'dist/',
        staticPath: '/',
        cssPath: '',
        imgPath: '',
        filenameHash: false,
    },
    development: {
        // 开发 devServer 端口
        port: 8089,
        devtool: 'source-map',
        NODE_ENV: 'development',
        jsSourceMap: false,
        cssSourceMap: false,
        eslint: false,
        filePath: 'dist/',
        staticPath: '/',
        cssPath: '',
        imgPath: '',
        filenameHash: false,
    }
};
